version: "3.9"
services:
  backend:
    build:
      context: ../app
    ports:
      - "3005:3005"
    environment:
      - MONGO_URI=mongodb://mongo:27017/app-contable
    depends_on:
      - mongo

  frontend:
    build:
      context: ../frontend
    ports:
      - "5173:80"

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
